name: "build"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
   GODOT_VERSION: 4.0
   EXPORT_NAME: {{ repo }}
   PROJECT_PATH: 
   

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-22.10
    container: docker://ghcr.io/VaguelyDamp/godot4b10:latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
          
  export-linux:
    name: Windows Export
  export-macos:
    name: Windows Export
  export-web:
    name: Windows Export